### ISSUE TITLE
El Modulo Firma Digial CCSS no reconoce donde esta libASEP11.so

### ISSUE THREAD

**Issue by FvD** [luisza/instaladoresFirmaDigitalCR#5]
Muy bueno que traten de facilitar este proceso. Gracias. Yo primero seguí las instrucciones escritas en fran.cr y funciona en la prueba en soportefirmadigital.cr pero no cuando trato de ingresar las paginas de [firma digital de la CCSS](https://aissfa.ccss.sa.cr/ModuloFirmaDigital/index.jsp). Da el siguiente error:

![problema_ccss](https://cloud.githubusercontent.com/assets/2441145/25154964/07ec8952-2450-11e7-8437-4cee5d97ce1c.png)

Pareciera que esto soluciona el problema:

    sudo ln -s /usr/lib/x86_64-linux-gnu/pkcs11/libASEP11.so /usr/local/lib/

pero no, se repite el mismo error en las paginas de la CCSS. Despues traté de usar el instaladar (Ubuntu 16.04), pero tampoco resuelve este problema.

Es perfectamente posible que el error esté en la pagina de la caja. Pero a lo mejor ustedes le encuentran unas solución.

**Comment by luisza** [comment]
Hola, 
Parece que el error es del applet de CCSS, ya hice la consulta en soporte y quedo a la espera de lo que me respondan ahí.

**Comment by ghost** [comment]
Hola:

La CCSS tiene 2 applets: el primero es el de autenticación, luego tiene otro para firmar un acuerdo de uso de varios módulos y para firmar documentos. El mensaje que muestra es del applet de autenticación, sin embargo esa ruta a la librería solo la utiliza el applet de firma. Hace unos meses publiqué este artículo con las rutas que requiere el de autenticación, que son distintas a las que aparecen en ese mensaje de error: 

https://fran.cr/como-autenticarse-en-el-modulo-de-firma-digital-de-la-ccss-en-gnulinux/

Nota: he detectado que el applet de autenticación puede fallar al buscar los certificados de la tarjeta si ésta contiene más certificados de lo habitual, por ejemplo, si se añadieron los certificados intermedios de la jerarquía o algún otro de uso personal. Esto no es lo habitual y afortunadamente casi nadie modifica el contenido de las tarjetas.

Saludos.

**Comment by luisza** [comment]
Cierto lo había olvidado, voy a corregir los instaladores para que copien los certificados y la biblioteca en su respectivo lugar.
Creo que es un parche feo, pero es bueno darle soporte a CCSS.

**Comment by luisza** [comment]
Actualicé el repositorio con una nueva versión de firmadigitalcr.
Hay un bug reportado que a veces  provoca errores en el instalador, esta versión además lo corrige, pero es posible que deban desinstalarlo (no actualizarlo) y luego instalarlo.

**Comment by ghost** [comment]
Gracias, aunque parece que la actualización del script del instalador todavía no incluye un enlace simbólico de la librería en `/usr/local/lib/`, donde el firmador (no el autenticador) de la CCSS sí lo requiere después.

**Comment by luisza** [comment]
Ya subí una nueva versión :)

**Comment by arielramos** [comment]
Buenos días, mucho gusto.

Estoy teniendo el mismo problema, pero en macOS, aunque yo tengo el procesador M1, lo probé en un modelo con Intel y sucede lo mismo, adicionalmente, las computadoras tienen diferentes versiones de S.O (BigSur y Ventura), pero el problema persiste.

<img width="143" alt="Screenshot 2023-07-07 at 8 58 47 AM" src="https://github.com/luisza/instaladoresFirmaDigitalCR/assets/11698932/22f50e80-8eaf-4f97-a623-ccc1e747fdb0">
<img width="1064" alt="Screenshot 2023-07-07 at 9 00 01 AM" src="https://github.com/luisza/instaladoresFirmaDigitalCR/assets/11698932/66a84598-aaa6-458e-b219-47ee5095ca9b">


Hay algo que es importante recalcar, intenté firmar con el Firmador Libre, y tampoco reconoce el certificado, aunque el GAUDI está conectado, pero, yo puedo firmar con Adobe Acrobat sin problemas, con eso confirmo que la instalación está bien.

<img width="1231" alt="Screenshot 2023-07-07 at 8 55 36 AM" src="https://github.com/luisza/instaladoresFirmaDigitalCR/assets/11698932/7904b812-221e-48ca-9115-773b28f8fb26">

He corroborado que el archivo .dylib exista en la ruta indicada por el instalador de la CCSS y en efecto ahí está:

<img width="541" alt="Screenshot 2023-07-07 at 9 01 57 AM" src="https://github.com/luisza/instaladoresFirmaDigitalCR/assets/11698932/c01589bc-debe-4c78-b641-ead95daa0e28">

Y hay otro archivo igual, pero en la ruta donde lo instala el firmador digital:

<img width="458" alt="Screenshot 2023-07-07 at 9 02 15 AM" src="https://github.com/luisza/instaladoresFirmaDigitalCR/assets/11698932/c502a1ea-b92a-4a7e-aa12-3021f82e885b">

Muchas gracias por la ayuda

**Comment by francoag2310** [comment]
Tengo el mismo error de arriba, algun update en esto?

**Comment by chacocr** [comment]
Hola,

El BCCR esta con problemas y todo esta caido.

Saludos

**Comment by francoag2310** [comment]
Tambien he notado que la libreria `libASEP11.dylib` es para x86. 

Si logro hacerlo funcionar el arm64 publicare los pasos

Gracias de paso @chacocr

**Comment by JosephTico** [comment]
Efectivamente solo está en x86 (y los del soporte son demasiado inútiles para soportar ARM), por lo que no va a lograr que sirva en Java a menos que instale la versión de x86 y lo corra con Rosetta.

En Adobe, si puede funcionar, pero asegurense que esta opción esté desactivada

![Acrobat Reader 15-01-15 at 05 49 PM](https://github.com/luisza/instaladoresFirmaDigitalCR/assets/8814190/cbb1a9cd-4bd5-417f-a9f3-2d50620ad6f3)

**Comment by arielramos** [comment]
Les comparto la solución al problema, hice un video en mi canal de Youtube: https://www.youtube.com/watch?v=vA4mpMHxkY8

**Comment by juanfelixh** [comment]
Alguien me puede facilitar el correo, o número para consultar? La sección de Pago a Proveedores, en el módulo de firma digital, da un error de: No se puede acceder a este Sitio Web. Los demás si cargan. Alguien que pueda probar o facilitarme la información de soporte? Gracias

**Comment by luisza** [comment]
Hola, mira debes considerar que en el país se está migrando hacia tarjetas con controladores JCOP4, que podría ser el caso, además tendrías que buscar si el aplicativo de la CCSS presenta algún error en dicha página. 
Lamentablemente tenemos pocos recursos para atender casos que están fuera del alcance del proyecto.
Como recomendación sabemos que hay algunos problemas si GAUDI está abierto con firmador libre pues no se detectan las tarjetas, podría ser un caso parecido en la app de CCSS.
