### ISSUE TITLE
Permitir applets Java en Firefox 52 y posteriores.

### ISSUE THREAD

**Issue by ghost** [luisza/instaladoresFirmaDigitalCR#6]
A partir de Firefox 52 RR (Rapid Release, versionamiento predeterminado) se desactiva el soporte NPAPI (excepto en la versión 52 ESR). Por el momento existe una opción para activarlo para todos los usuarios, pero es algo provisional, no documentado y podrían eliminarlo en cualquier momento en versiones futuras. En cualquier caso, tal vez pueda servir para mantener los applets Java activos en RR unos meses más.

La técnica propuesta se basa en el mecanismo de configuración de ambientes enterprise de Firefox, que mediante un fichero .js se pueden agregar parámetros como los que hay en about:config para todos los usuarios de la máquina.

Este ejemplo debería funcionar si se crea un fichero con extensión .js

```javascript
/* Forces support NPAPI plugins since version Firefox 52 to support Java applets */    
pref("plugin.load_flash_only", false);
```

En Fedora lo he guardado como `/usr/lib64/firefox/defaults/pref/enable-java.js`. En Debian y derivados creo que debe crearse el fichero .js en `/usr/lib/firefox/defaults/pref/`. Hay que reiniciar el navegador para que funcionen los cambios.

Lo he probado con Firefox 53 y todavía funciona. Tal vez merezca la pena darle soporte a esto en el instalador, ya que es habitual que la administración pública tarde su tiempo en adaptarse a los nuevos sistemas como el firmador del BCCR y mecanismos parecidos.

**Comment by luisza** [comment]
Suena interesante, en estos días estoy un poco ocupado con otras cosas pero podría ser bueno incluirlo.

**Comment by fdelapena** [comment]
Parece que ya no funciona en Firefox 54 😢, ahora habrá que usar Firefox ESR hasta que a mediados de 2018 no haya otra opción mantenida.

**Comment by ghost** [comment]
Ya no funciona en Firefox 54. La única solución en Debian y Ubuntu es usar Firefox ESR y en Fedora usar Icecat. La versión ESR no requiere este parche, por lo que se puede descartar.
